name: Sanity Check

on:
  workflow_run:
    workflows:
      - Test
    types:
      - completed
      - requested
      - in_progress

jobs:
  always:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "Event action: ${{ github.event.action}}"'
